/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliverysystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class order_status_update extends javax.swing.JInternalFrame {

    /**
     * Creates new form order_status_update
     */
    public order_status_update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Status Update");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Status");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(41, 91, 80, 25);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Status", "Pending", "Completed", "Cancelled" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(126, 86, 109, 35);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/Starcraft-2-Editor-2-icon.png"))); // NOI18N
        jButton1.setText("Update Status");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(115, 154, 165, 57);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Order No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(37, 29, 70, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(125, 26, 110, 22);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/V/s2.jpg"))); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(247, 24, 95, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/15.JPG"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-39, -64, 510, 410);

        setBounds(0, 0, 427, 320);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         Connection myconnection;
        String path="jdbc:mysql://localhost/";
        String place="deliverysystemdb";
        String username="root";
        String password="";
        try
        {
            myconnection =DriverManager.getConnection(path+place,username,password);
            try
            {
                String q="update ordertable set status=?"+"where orderno=?";
                PreparedStatement ms =myconnection.prepareStatement(q);

                
               
                
                 ms.setString(1, jComboBox6.getSelectedItem().toString());
                ms.setString(2, jTextField1.getText());
                

               

                if(ms.executeUpdate()>0)
                {

                  
                  JOptionPane.showMessageDialog(rootPane,"Record Updated successfully ");
                  
                  
                    jComboBox6.setSelectedIndex(0);
                    jTextField1.setText("");
                   
                    }

                }

                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         Connection myconnection;
        String path="jdbc:mysql://localhost/";
        String place="deliverysystemdb";
        String username="root";
        String password="";
        try
        {
            myconnection =DriverManager.getConnection(path+place,username,password);
            try
            {   
                String q="select* from ordertable where orderno=?";
                PreparedStatement ms =myconnection.prepareStatement(q);
                
                 ms.setString(1, jTextField1.getText());
                 ResultSet myresult=ms.executeQuery();
                 if(myresult.next())
                 {
                     
                     jComboBox6.setSelectedItem(myresult.getString("status"));
                     
                     JOptionPane.showMessageDialog(rootPane,"Record showed successfully ");
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(rootPane,"No record found ");
                      jComboBox6.setSelectedIndex(0);
                 }
                    
                     
                 
                 
                
            }
           
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
                    }
            finally
            {
                myconnection.close();
            }
            
        }
        catch(Exception e)
                {
                   JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
                }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
