/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliverysystem;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author HP
 */
public class search_order extends javax.swing.JInternalFrame {

    /**
     * Creates new form search_order
     */
    public search_order() {
        initComponents();
        if(parentframe_admin.usertype==null){jTextField1.setText(parentframe_employee.orderno);
        }
        else {jTextField1.setText(parentframe_admin.orderno);
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Search Order");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jLabel1.setText("Order No.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(23, 122, 97, 27);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(125, 122, 170, 22);

        jLabel2.setText("Order Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(23, 216, 97, 24);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(130, 220, 125, 24);

        jLabel3.setText("Location");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(14, 299, 97, 36);

        jLabel4.setText("Country");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(458, 258, 108, 28);

        jLabel5.setText("State");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(374, 258, 66, 28);

        jLabel6.setText("City");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(285, 258, 71, 28);

        jLabel7.setText("Area");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(203, 258, 64, 28);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(460, 310, 72, 30);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(370, 310, 66, 30);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(280, 310, 77, 28);
        jPanel1.add(jLabel17);
        jLabel17.setBounds(213, 300, 60, 36);

        jLabel21.setText("House No.");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(115, 264, 72, 16);
        jPanel1.add(jLabel22);
        jLabel22.setBounds(115, 299, 72, 31);

        jLabel8.setText("Category");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(14, 390, 70, 29);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(107, 499, 93, 45);

        jLabel9.setText("Ordered Goods");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(14, 450, 86, 31);

        jLabel10.setText("Price");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(14, 513, 86, 31);

        jLabel12.setText("Status");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(14, 557, 86, 28);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(96, 390, 93, 29);
        jPanel1.add(jLabel19);
        jLabel19.setBounds(120, 450, 96, 31);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(107, 557, 85, 28);

        jLabel23.setText("Phone No.");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(244, 382, 112, 37);
        jPanel1.add(jLabel24);
        jLabel24.setBounds(363, 382, 113, 37);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(130, 170, 200, 27);

        jLabel25.setText("Customer Name");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(23, 167, 92, 26);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setText("ANKIT COURIER COMPANY");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(110, 20, 328, 29);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("8054997115");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(520, 20, 131, 29);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setText("RECEIPT");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(230, 60, 131, 43);

        jTextField6.setEditable(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(326, 460, 110, 22);

        jLabel29.setText("Weight(in Kg)");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(240, 460, 90, 16);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/145.JPG"))); // NOI18N
        jPanel1.add(jLabel30);
        jLabel30.setBounds(-12, -4, 700, 610);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 60, 680, 600);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/App-xmag-search-icon.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 10, 109, 41);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/printer-icon.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 0, 111, 57);

        setBounds(0, 0, 961, 709);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        Connection myconnection;
        String path="jdbc:mysql://localhost/";
        String place="deliverysystemdb";
        String username="root";
        String password="";
        try
        {
            myconnection =DriverManager.getConnection(path+place,username,password);
            try
            {
                String q="select* from ordertable where orderno=?";
                PreparedStatement ms =myconnection.prepareStatement(q);

                ms.setString(1, jTextField1.getText());
                ResultSet myresult=ms.executeQuery();
                if(myresult.next())
                {
                    jLabel13.setText(myresult.getString("orderdate"));
                    jLabel19.setText(myresult.getString("goodsname"));
                    jLabel11.setText(myresult.getString("price"));
                    jLabel18.setText(myresult.getString("categoryname"));
                    jLabel14.setText(myresult.getString("countryname"));
                    jLabel15.setText(myresult.getString("statename"));
                    jLabel16.setText(myresult.getString("cityname"));
                    jLabel17.setText(myresult.getString("areaname"));
                    jLabel20.setText(myresult.getString("status"));
                    jLabel22.setText(myresult.getString("houseno"));
                    jLabel24.setText(myresult.getString("phone"));
                     jTextField5.setText(myresult.getString("cname"));
                     jTextField6.setText(myresult.getString("weight"));
                        
                      JOptionPane.showMessageDialog(rootPane,"Record showed successfully ");
                }

               
                
                 else
                            {
                             JOptionPane.showMessageDialog(rootPane,"No Record Founds ");
                             jTextField1.setText("");
                    jLabel13.setText("");
                    jLabel14.setText("");
                    jLabel15.setText("");
                    jLabel16.setText("");
                    jLabel17.setText("");
                    jLabel18.setText("");
                    jLabel19.setText("");
                    jLabel20.setText("");
                    jLabel11.setText("");
                    jTextField5.setText("");
                      jTextField6.setText("");
                             
                             }

            }

            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
            }
            finally
            {
                myconnection.close();
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        PrinterJob job = PrinterJob.getPrinterJob();
    job.setJobName("Print Java Component");
 
    job.setPrintable (new Printable() {    
        public int print(Graphics g, PageFormat pageFormat, int pageIndex) {
            if (pageIndex > 0) {
                return(NO_SUCH_PAGE);
            } else {
                Graphics2D g2d = (Graphics2D)g;
                g2d.translate(pageFormat.getImageableX(), 
                pageFormat.getImageableY());
 
                jPanel1.paint(g2d);
 
                return(PAGE_EXISTS); 
            }
        }
    });
         
    if (job.printDialog()) {
        try {
            job.print();
        } catch (PrinterException e) {
            System.err.println(e.getMessage()); 
        }
    } 
         
        
//        Toolkit tkp = jPanel1.getToolkit();
//               parentframe_admin obj1=new parentframe_admin();
//        
//         
//    PrintJob pjp = tkp.getPrintJob(obj1, null, null);
//         Graphics g = pjp.getGraphics();
//    jPanel1.print(g);
//    g.dispose();
//    pjp.end();
//        
        
//         if(parentframe_admin.usertype==null){
//              Toolkit tkp = jPanel1.getToolkit();
//               parentframe_employee obj1=new parentframe_employee();
//        
//         
//    PrintJob pjp = tkp.getPrintJob(obj1, null, null);
//         Graphics g = pjp.getGraphics();
//    jPanel1.print(g);
//    g.dispose();
//    pjp.end();}
//         else
//         { Toolkit tkp = jPanel1.getToolkit();
//          parentframe_admin obj=new parentframe_admin();
//             PrintJob pjp = tkp.getPrintJob(obj, null, null);
//                     Graphics g = pjp.getGraphics();
//    jPanel1.print(g);
//    g.dispose();
//    pjp.end();
//         }
   

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
             Connection myconnection;
        String path="jdbc:mysql://localhost/";
        String place="deliverysystemdb";
        String username="root";
        String password="";
        try
        {
            myconnection =DriverManager.getConnection(path+place,username,password);
            try
            {
                String q="select* from ordertable where orderno=?";
                PreparedStatement ms =myconnection.prepareStatement(q);

                ms.setString(1, jTextField1.getText());
                ResultSet myresult=ms.executeQuery();
                if(myresult.next())
                {
                    jLabel13.setText(myresult.getString("orderdate"));
                    jLabel19.setText(myresult.getString("goodsname"));
                    jLabel11.setText(myresult.getString("price"));
                    jLabel18.setText(myresult.getString("categoryname"));
                    jLabel14.setText(myresult.getString("countryname"));
                    jLabel15.setText(myresult.getString("statename"));
                    jLabel16.setText(myresult.getString("cityname"));
                    jLabel17.setText(myresult.getString("areaname"));
                    jLabel20.setText(myresult.getString("status"));
                    jLabel22.setText(myresult.getString("houseno"));
                    jLabel24.setText(myresult.getString("phone"));

                }

                JOptionPane.showMessageDialog(rootPane,"Record showed successfully ");

            }

            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
            }
            finally
            {
                myconnection.close();
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
        }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
