/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliverysystem;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class vehicle extends javax.swing.JInternalFrame {

    /**
     * Creates new form employee
     */
    
    
    public vehicle() {
        initComponents();
        
        if(parentframe_admin.usertype==null){jButton2.setVisible(false);
         jButton4.setVisible(false);
         jButton5.setVisible(false);
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Vehicle");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jLabel1.setText("Vehicle No.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(34, 15, 77, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(116, 19, 160, 22);

        jLabel2.setText("Vehicle Company");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(34, 65, 100, 29);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(138, 68, 140, 22);

        jLabel3.setText("Engine Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(34, 112, 90, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(128, 116, 150, 22);

        jLabel4.setText("Name And Model No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(34, 160, 120, 25);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(158, 160, 120, 96);

        jLabel5.setText("Wheeler");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 280, 77, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Two");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(130, 280, 53, 30);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Three");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(180, 280, 63, 30);

        jLabel6.setText("Date Of Registration");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(34, 348, 120, 24);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(165, 348, 120, 22);

        jLabel7.setText("Chasis Number");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(34, 395, 90, 26);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(135, 397, 150, 22);

        jLabel8.setText("Colour");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(34, 448, 37, 24);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(125, 449, 160, 22);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Four");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(240, 280, 70, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/145.JPG"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-22, -24, 640, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 580, 500);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/S/Add-icon.png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(640, 30, 110, 25);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/S/search.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(640, 105, 110, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/S/software_update.png"))); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(640, 175, 110, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/S/Capture.PNG"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(640, 260, 110, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deliverysystem/images/printer-icon - Copy.png"))); // NOI18N
        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(640, 320, 110, 33);

        setBounds(0, 0, 803, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
      
        Connection myconnection;
        String path="jdbc:mysql://localhost/";
        String place="deliverysystemdb";
        String username="root";
        String password="";
        try
        {
            myconnection =DriverManager.getConnection(path+place,username,password);
            try
            {
                String q="insert into vehicle(no,comp,eng,name,wheeler,dor,chasis,col)value(?,?,?,?,?,?,?,?)";
                PreparedStatement ms =myconnection.prepareStatement(q);
                
                 ms.setString(1, jTextField1.getText());
                 ms.setString(2, jTextField2.getText());
                 ms.setString(3, jTextField3.getText());
                 ms.setString(7, jTextField4.getText());
                 ms.setString(4, jTextArea1.getText());
                
               
                 java.util.Date cdate1=new java.util.Date();
                 SimpleDateFormat myformat1=new SimpleDateFormat("yyyy-MM-dd");
               
                 ms.setString(8, jTextField4.getText());
                 
                 
                 if(jRadioButton1.isSelected())
                 {
                     ms.setString(5, "Two");
                 }
                 else if(jRadioButton2.isSelected())
                 {
                     ms.setString(5, "Three");
                 }
                 else if(jRadioButton3.isSelected())
                {
                     ms.setString(5, "Four");
                 }
                 
                 SimpleDateFormat myformat=new SimpleDateFormat("yyyy-MM-dd");
               
                 ms.setString(6, myformat.format(jDateChooser1.getDate()));
                 
                 
                 if(ms.executeUpdate()>0)
                 {
                     
                  
        
                     JOptionPane.showMessageDialog(rootPane,"Record stored successfully ");
                    
                  
                  
                  jTextField5.setText("");
                  
                  jTextField1.setText("");
                  
                  jTextArea1.setText("");
                  buttonGroup1.clearSelection();
                  
                 
                  jDateChooser1.setDate(null);
                  jTextField2.setText("");
                  jTextField4.setText("");
                  
                  jTextField3.setText("");
                  
                
      }
                  
                  
                  
                  
                     
                     
                 
                 
                
            }
           
            catch(Exception e)
                    {
                         JOptionPane.showMessageDialog(rootPane,"Fill in all the fields");
                    }
            finally
            {
                myconnection.close();
            }
            
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        
        
         Connection myconnection;
        String path="jdbc:mysql://localhost/";
        String place="deliverysystemdb";
        String username="root";
        String password="";
        try
        {
            myconnection =DriverManager.getConnection(path+place,username,password);
            try
            {   //String q="insert into boypersonal(empid,name,fathername,phone,address,gender,dob,age,bgroup)value(?,?,?,?,?,?,?,?,?)";
                String q="select* from vehicle where no=?";
                PreparedStatement ms =myconnection.prepareStatement(q);

                ms.setString(1, jTextField1.getText());
                ResultSet myresult=ms.executeQuery();
                if(myresult.next())
                {   
                    jTextField2.setText(myresult.getString("comp"));
                     jTextField4.setText(myresult.getString("chasis"));
                   
                   jTextField3.setText(myresult.getString("eng"));
                    jTextArea1.setText(myresult.getString("name"));
                   
                   if(myresult.getString("wheeler").equals("Two"))
                     {
                        jRadioButton1.setSelected(true);
                     }
                     else if(myresult.getString("wheeler").equals("Three"))
                     {
                        jRadioButton2.setSelected(true);
                     }
                   
                    else if(myresult.getString("wheeler").equals("Four"))
                     {
                        jRadioButton3.setSelected(true);
                     }
                   jDateChooser1.setDate(myresult.getDate("dor"));
                  jTextField5.setText(myresult.getString("col"));
                  
                   JOptionPane.showMessageDialog(rootPane,"Record showed successfully ");
                 

                       

                }

                
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"No Record Found ");
                    
                    jTextField5.setText("");
                  
                  jTextField1.setText("");
                  
                  jTextArea1.setText("");
                  buttonGroup1.clearSelection();
                  
                 
                  jDateChooser1.setDate(null);
                  jTextField2.setText("");
                  jTextField4.setText("");
                  
                  jTextField3.setText("");
                  
                
                              
                }

            }

            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
            }
            finally
            {
                myconnection.close();
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        Connection myconnection;
        String path="jdbc:mysql://localhost/";
        String place="deliverysystemdb";
        String username="root";
        String password="";
        try
        {
            myconnection =DriverManager.getConnection(path+place,username,password);
            try
            {
                String q="update vehicle set comp=?,eng=?,name=?,wheeler=?,dor=?,chasis=?,col=?"+"where no=?";
                PreparedStatement ms =myconnection.prepareStatement(q);
                 
                 
                ms.setString(1, jTextField2.getText());
                ms.setString(2, jTextField3.getText());
                ms.setString(8, jTextField1.getText());
                  ms.setString(6, jTextField4.getText());
                    ms.setString(7, jTextField5.getText());
             
                ms.setString(3, jTextArea1.getText());
               if(jRadioButton1.isSelected())
                 {
                     ms.setString(4, "Two");
                 }
                 else if(jRadioButton2.isSelected())
                 {
                     ms.setString(4, "Three");
                 }
                 else if(jRadioButton3.isSelected())
                {
                     ms.setString(4, "Four");
                 }
               
               

                SimpleDateFormat myformat=new SimpleDateFormat("yyyy-MM-dd");

                ms.setString(5, myformat.format(jDateChooser1.getDate()));

                if(ms.executeUpdate()>0)
                {

                            JOptionPane.showMessageDialog(rootPane,"Record updated successfully ");
                            
                            jTextField5.setText("");
                  
                  jTextField1.setText("");
                  
                  jTextArea1.setText("");
                  buttonGroup1.clearSelection();
                  
                 
                  jDateChooser1.setDate(null);
                  jTextField2.setText("");
                  jTextField4.setText("");
                  
                  jTextField3.setText("");
                  
                 
                            
                            
                    }
                
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"No Record Found ");
                    
                    jTextField5.setText("");
                  
                  jTextField1.setText("");
                  
                  jTextArea1.setText("");
                  buttonGroup1.clearSelection();
                  
                 
                  jDateChooser1.setDate(null);
                  jTextField2.setText("");
                  jTextField4.setText("");
                  
                  jTextField3.setText("");
                  
                
                              
                }

                }

                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        int answer=JOptionPane.showConfirmDialog(rootPane, "Do you really want to delete", "Confirm",JOptionPane.YES_NO_OPTION);
        if(answer==JOptionPane.YES_OPTION)
        {
            Connection myconnection;
        String path="jdbc:mysql://localhost/";
        String place="deliverysystemdb";
        String username="root";
        String password="";
        try
        {
            myconnection =DriverManager.getConnection(path+place,username,password);
            try
            {
                String q="delete from vehicle where no=?";
                PreparedStatement ms =myconnection.prepareStatement(q);

               
                ms.setString(1, jTextField1.getText());

                if(ms.executeUpdate()>0){
                    JOptionPane.showMessageDialog(rootPane,"Record deleted successfully ");
                    
                    
                     jTextField5.setText("");
                  
                  jTextField1.setText("");
                  
                  jTextArea1.setText("");
                  buttonGroup1.clearSelection();
                  
                 
                  jDateChooser1.setDate(null);
                  jTextField2.setText("");
                  jTextField4.setText("");
                  
                  jTextField3.setText("");
                  
               
                    

                }
                
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"No Record Found ");
                    
                    jTextField5.setText("");
                  
                  jTextField1.setText("");
                  
                  jTextArea1.setText("");
                  buttonGroup1.clearSelection();
                  
                 
                  jDateChooser1.setDate(null);
                  jTextField2.setText("");
                  jTextField4.setText("");
                  
                  jTextField3.setText("");
                  
                
                              
                }

            }

            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
            }
            finally
            {
                myconnection.close();
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error in query "+e.getMessage());
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        PrinterJob job = PrinterJob.getPrinterJob();
    job.setJobName("Print Java Component");
 
    job.setPrintable (new Printable() {    
        public int print(Graphics g, PageFormat pageFormat, int pageIndex) {
            if (pageIndex > 0) {
                return(NO_SUCH_PAGE);
            } else {
                Graphics2D g2d = (Graphics2D)g;
                g2d.translate(pageFormat.getImageableX(), 
                pageFormat.getImageableY());
 
                jPanel1.paint(g2d);
               
 
                return(PAGE_EXISTS); 
            }
        }
    });
         
    if (job.printDialog()) {
        try {
            job.print();
        } catch (PrinterException e) {
            System.err.println(e.getMessage()); 
        }
    } 
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
